---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      ExcessiveMethodLength:
        minimum: 50
      ShortVariable:
        minimum: 1
      ElseExpression:
        enabled: false
      ExcessiveClassLength:
        minimum: 1000
ratings:
  paths:
  - "**.inc"
  - "**.ctp"
  - "**.module"
  - "**.php"
exclude_paths:
- config/
- tests/
- webroot/